### ISSUE TITLE
Create or Design Hactoberfest page

### ISSUE THREAD

**Issue by kevalvavaliya** [Bauddhik-Geeks/Bauddhik-Geeks.github.io#11]
create a hactoberfest page to link with the website

**Comment by prathamesh-borse** [comment]
@kevalvavaliya Can u please let me know what exactly we have to add in the Hacktoberfest Page?

**Comment by kevalvavaliya** [comment]
I have shared the sample links in the server can you check there.

**Comment by prathamesh-borse** [comment]
> I have shared the sample links in the server can you check there.

Yes, I have checked that and currently, I am working on it.!
